FROM python:3.6-alpine
MAINTAINER Karthik "karthik.velagandula@jotter.ai"
#VOLUME ["/app/images"]
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY images /app/
COPY static /app/static
COPY app.py /app/app.py
COPY templates /app/templates
CMD ["python", "app.py"]
